// Best-effort IANA timezone -> country mapping, used to derive an
// approximate visitor country from the browser's own
// Intl.DateTimeFormat().resolvedOptions().timeZone — deliberately not from
// the IP address, so no geo-IP lookup/database/service is needed at all.
// Not exhaustive (the IANA tz database has ~400 zones covering every
// timezone-distinct region, many of which map to the same country) — covers
// every zone likely to matter for this app's audience; anything unmapped
// resolves to { country: null, countryCode: null } rather than a guess.
export const TIMEZONE_COUNTRIES = {
  "Asia/Kolkata": { country: "India", countryCode: "IN" },
  "Asia/Calcutta": { country: "India", countryCode: "IN" },
  "Asia/Karachi": { country: "Pakistan", countryCode: "PK" },
  "Asia/Dhaka": { country: "Bangladesh", countryCode: "BD" },
  "Asia/Colombo": { country: "Sri Lanka", countryCode: "LK" },
  "Asia/Kathmandu": { country: "Nepal", countryCode: "NP" },
  "Asia/Kabul": { country: "Afghanistan", countryCode: "AF" },
  "Asia/Dubai": { country: "United Arab Emirates", countryCode: "AE" },
  "Asia/Riyadh": { country: "Saudi Arabia", countryCode: "SA" },
  "Asia/Qatar": { country: "Qatar", countryCode: "QA" },
  "Asia/Bahrain": { country: "Bahrain", countryCode: "BH" },
  "Asia/Kuwait": { country: "Kuwait", countryCode: "KW" },
  "Asia/Muscat": { country: "Oman", countryCode: "OM" },
  "Asia/Baghdad": { country: "Iraq", countryCode: "IQ" },
  "Asia/Tehran": { country: "Iran", countryCode: "IR" },
  "Asia/Amman": { country: "Jordan", countryCode: "JO" },
  "Asia/Beirut": { country: "Lebanon", countryCode: "LB" },
  "Asia/Damascus": { country: "Syria", countryCode: "SY" },
  "Asia/Jerusalem": { country: "Israel", countryCode: "IL" },
  "Asia/Gaza": { country: "Palestine", countryCode: "PS" },
  "Asia/Hebron": { country: "Palestine", countryCode: "PS" },
  "Asia/Istanbul": { country: "Turkey", countryCode: "TR" },
  "Europe/Istanbul": { country: "Turkey", countryCode: "TR" },
  "Asia/Yerevan": { country: "Armenia", countryCode: "AM" },
  "Asia/Baku": { country: "Azerbaijan", countryCode: "AZ" },
  "Asia/Tbilisi": { country: "Georgia", countryCode: "GE" },
  "Asia/Almaty": { country: "Kazakhstan", countryCode: "KZ" },
  "Asia/Tashkent": { country: "Uzbekistan", countryCode: "UZ" },
  "Asia/Bishkek": { country: "Kyrgyzstan", countryCode: "KG" },
  "Asia/Dushanbe": { country: "Tajikistan", countryCode: "TJ" },
  "Asia/Ashgabat": { country: "Turkmenistan", countryCode: "TM" },
  "Asia/Yangon": { country: "Myanmar", countryCode: "MM" },
  "Asia/Bangkok": { country: "Thailand", countryCode: "TH" },
  "Asia/Jakarta": { country: "Indonesia", countryCode: "ID" },
  "Asia/Makassar": { country: "Indonesia", countryCode: "ID" },
  "Asia/Jayapura": { country: "Indonesia", countryCode: "ID" },
  "Asia/Kuala_Lumpur": { country: "Malaysia", countryCode: "MY" },
  "Asia/Singapore": { country: "Singapore", countryCode: "SG" },
  "Asia/Manila": { country: "Philippines", countryCode: "PH" },
  "Asia/Ho_Chi_Minh": { country: "Vietnam", countryCode: "VN" },
  "Asia/Phnom_Penh": { country: "Cambodia", countryCode: "KH" },
  "Asia/Vientiane": { country: "Laos", countryCode: "LA" },
  "Asia/Brunei": { country: "Brunei", countryCode: "BN" },
  "Asia/Hong_Kong": { country: "Hong Kong", countryCode: "HK" },
  "Asia/Macau": { country: "Macau", countryCode: "MO" },
  "Asia/Shanghai": { country: "China", countryCode: "CN" },
  "Asia/Chongqing": { country: "China", countryCode: "CN" },
  "Asia/Urumqi": { country: "China", countryCode: "CN" },
  "Asia/Taipei": { country: "Taiwan", countryCode: "TW" },
  "Asia/Seoul": { country: "South Korea", countryCode: "KR" },
  "Asia/Pyongyang": { country: "North Korea", countryCode: "KP" },
  "Asia/Tokyo": { country: "Japan", countryCode: "JP" },
  "Asia/Ulaanbaatar": { country: "Mongolia", countryCode: "MN" },

  "Europe/London": { country: "United Kingdom", countryCode: "GB" },
  "Europe/Dublin": { country: "Ireland", countryCode: "IE" },
  "Europe/Lisbon": { country: "Portugal", countryCode: "PT" },
  "Europe/Madrid": { country: "Spain", countryCode: "ES" },
  "Europe/Paris": { country: "France", countryCode: "FR" },
  "Europe/Brussels": { country: "Belgium", countryCode: "BE" },
  "Europe/Amsterdam": { country: "Netherlands", countryCode: "NL" },
  "Europe/Luxembourg": { country: "Luxembourg", countryCode: "LU" },
  "Europe/Berlin": { country: "Germany", countryCode: "DE" },
  "Europe/Zurich": { country: "Switzerland", countryCode: "CH" },
  "Europe/Vienna": { country: "Austria", countryCode: "AT" },
  "Europe/Rome": { country: "Italy", countryCode: "IT" },
  "Europe/Malta": { country: "Malta", countryCode: "MT" },
  "Europe/Copenhagen": { country: "Denmark", countryCode: "DK" },
  "Europe/Oslo": { country: "Norway", countryCode: "NO" },
  "Europe/Stockholm": { country: "Sweden", countryCode: "SE" },
  "Europe/Helsinki": { country: "Finland", countryCode: "FI" },
  "Europe/Warsaw": { country: "Poland", countryCode: "PL" },
  "Europe/Prague": { country: "Czechia", countryCode: "CZ" },
  "Europe/Bratislava": { country: "Slovakia", countryCode: "SK" },
  "Europe/Budapest": { country: "Hungary", countryCode: "HU" },
  "Europe/Bucharest": { country: "Romania", countryCode: "RO" },
  "Europe/Sofia": { country: "Bulgaria", countryCode: "BG" },
  "Europe/Athens": { country: "Greece", countryCode: "GR" },
  "Europe/Belgrade": { country: "Serbia", countryCode: "RS" },
  "Europe/Zagreb": { country: "Croatia", countryCode: "HR" },
  "Europe/Sarajevo": { country: "Bosnia and Herzegovina", countryCode: "BA" },
  "Europe/Ljubljana": { country: "Slovenia", countryCode: "SI" },
  "Europe/Skopje": { country: "North Macedonia", countryCode: "MK" },
  "Europe/Tirane": { country: "Albania", countryCode: "AL" },
  "Europe/Chisinau": { country: "Moldova", countryCode: "MD" },
  "Europe/Kyiv": { country: "Ukraine", countryCode: "UA" },
  "Europe/Minsk": { country: "Belarus", countryCode: "BY" },
  "Europe/Riga": { country: "Latvia", countryCode: "LV" },
  "Europe/Vilnius": { country: "Lithuania", countryCode: "LT" },
  "Europe/Tallinn": { country: "Estonia", countryCode: "EE" },
  "Europe/Moscow": { country: "Russia", countryCode: "RU" },
  "Europe/Kaliningrad": { country: "Russia", countryCode: "RU" },
  "Europe/Reykjavik": { country: "Iceland", countryCode: "IS" },

  "Africa/Cairo": { country: "Egypt", countryCode: "EG" },
  "Africa/Tripoli": { country: "Libya", countryCode: "LY" },
  "Africa/Tunis": { country: "Tunisia", countryCode: "TN" },
  "Africa/Algiers": { country: "Algeria", countryCode: "DZ" },
  "Africa/Casablanca": { country: "Morocco", countryCode: "MA" },
  "Africa/Khartoum": { country: "Sudan", countryCode: "SD" },
  "Africa/Addis_Ababa": { country: "Ethiopia", countryCode: "ET" },
  "Africa/Nairobi": { country: "Kenya", countryCode: "KE" },
  "Africa/Dar_es_Salaam": { country: "Tanzania", countryCode: "TZ" },
  "Africa/Kampala": { country: "Uganda", countryCode: "UG" },
  "Africa/Kigali": { country: "Rwanda", countryCode: "RW" },
  "Africa/Mogadishu": { country: "Somalia", countryCode: "SO" },
  "Africa/Djibouti": { country: "Djibouti", countryCode: "DJ" },
  "Africa/Lagos": { country: "Nigeria", countryCode: "NG" },
  "Africa/Accra": { country: "Ghana", countryCode: "GH" },
  "Africa/Abidjan": { country: "Ivory Coast", countryCode: "CI" },
  "Africa/Dakar": { country: "Senegal", countryCode: "SN" },
  "Africa/Bamako": { country: "Mali", countryCode: "ML" },
  "Africa/Niamey": { country: "Niger", countryCode: "NE" },
  "Africa/Ouagadougou": { country: "Burkina Faso", countryCode: "BF" },
  "Africa/Conakry": { country: "Guinea", countryCode: "GN" },
  "Africa/Freetown": { country: "Sierra Leone", countryCode: "SL" },
  "Africa/Monrovia": { country: "Liberia", countryCode: "LR" },
  "Africa/Johannesburg": { country: "South Africa", countryCode: "ZA" },
  "Africa/Harare": { country: "Zimbabwe", countryCode: "ZW" },
  "Africa/Lusaka": { country: "Zambia", countryCode: "ZM" },
  "Africa/Maputo": { country: "Mozambique", countryCode: "MZ" },
  "Africa/Gaborone": { country: "Botswana", countryCode: "BW" },
  "Africa/Windhoek": { country: "Namibia", countryCode: "NA" },
  "Africa/Kinshasa": { country: "DR Congo", countryCode: "CD" },
  "Africa/Lubumbashi": { country: "DR Congo", countryCode: "CD" },
  "Africa/Luanda": { country: "Angola", countryCode: "AO" },
  "Africa/Bangui": { country: "Central African Republic", countryCode: "CF" },
  "Africa/Ndjamena": { country: "Chad", countryCode: "TD" },
  "Africa/Yaounde": { country: "Cameroon", countryCode: "CM" },

  "America/New_York": { country: "United States", countryCode: "US" },
  "America/Chicago": { country: "United States", countryCode: "US" },
  "America/Denver": { country: "United States", countryCode: "US" },
  "America/Phoenix": { country: "United States", countryCode: "US" },
  "America/Los_Angeles": { country: "United States", countryCode: "US" },
  "America/Anchorage": { country: "United States", countryCode: "US" },
  "Pacific/Honolulu": { country: "United States", countryCode: "US" },
  "America/Toronto": { country: "Canada", countryCode: "CA" },
  "America/Vancouver": { country: "Canada", countryCode: "CA" },
  "America/Edmonton": { country: "Canada", countryCode: "CA" },
  "America/Winnipeg": { country: "Canada", countryCode: "CA" },
  "America/Halifax": { country: "Canada", countryCode: "CA" },
  "America/St_Johns": { country: "Canada", countryCode: "CA" },
  "America/Mexico_City": { country: "Mexico", countryCode: "MX" },
  "America/Bogota": { country: "Colombia", countryCode: "CO" },
  "America/Lima": { country: "Peru", countryCode: "PE" },
  "America/Caracas": { country: "Venezuela", countryCode: "VE" },
  "America/Santiago": { country: "Chile", countryCode: "CL" },
  "America/Argentina/Buenos_Aires": { country: "Argentina", countryCode: "AR" },
  "America/Sao_Paulo": { country: "Brazil", countryCode: "BR" },
  "America/Montevideo": { country: "Uruguay", countryCode: "UY" },
  "America/Asuncion": { country: "Paraguay", countryCode: "PY" },
  "America/La_Paz": { country: "Bolivia", countryCode: "BO" },
  "America/Guayaquil": { country: "Ecuador", countryCode: "EC" },
  "America/Panama": { country: "Panama", countryCode: "PA" },
  "America/Costa_Rica": { country: "Costa Rica", countryCode: "CR" },
  "America/Guatemala": { country: "Guatemala", countryCode: "GT" },
  "America/Havana": { country: "Cuba", countryCode: "CU" },
  "America/Jamaica": { country: "Jamaica", countryCode: "JM" },
  "America/Port-au-Prince": { country: "Haiti", countryCode: "HT" },
  "America/Santo_Domingo": { country: "Dominican Republic", countryCode: "DO" },
  "America/Port_of_Spain": { country: "Trinidad and Tobago", countryCode: "TT" },

  "Australia/Sydney": { country: "Australia", countryCode: "AU" },
  "Australia/Melbourne": { country: "Australia", countryCode: "AU" },
  "Australia/Brisbane": { country: "Australia", countryCode: "AU" },
  "Australia/Perth": { country: "Australia", countryCode: "AU" },
  "Australia/Adelaide": { country: "Australia", countryCode: "AU" },
  "Australia/Darwin": { country: "Australia", countryCode: "AU" },
  "Australia/Hobart": { country: "Australia", countryCode: "AU" },
  "Pacific/Auckland": { country: "New Zealand", countryCode: "NZ" },
  "Pacific/Fiji": { country: "Fiji", countryCode: "FJ" },
  "Pacific/Port_Moresby": { country: "Papua New Guinea", countryCode: "PG" },
  "Pacific/Guam": { country: "Guam", countryCode: "GU" },
};

/** `tz` is the exact IANA identifier from the browser
 * (Intl.DateTimeFormat().resolvedOptions().timeZone). Returns
 * `{ country: null, countryCode: null }` for anything unmapped or
 * unrecognized rather than guessing. */
export function countryFromTimezone(tz) {
  return TIMEZONE_COUNTRIES[tz] || { country: null, countryCode: null };
}
