import Degree from "../models/Degree.js";

const DEFAULTS = [
  "Secondary (10th)",
  "Senior Secondary (12th)",
  "ITI Certificate",
  "Diploma",
  "D.El.Ed. (Diploma in Elementary Education)",
  "D.Pharm. (Diploma in Pharmacy)",
  "BA LLB (Integrated)",
  "BBA LLB (Integrated)",
  "B.A.",
  "B.Sc.",
  "B.Com.",
  "BBA",
  "BCA",
  "B.El.Ed.",
  "BJMC (Journalism & Mass Communication)",
  "B.Lib.Sc.",
  "B.Tech.",
  "B.E.",
  "B.Arch.",
  "B.Des.",
  "BFA",
  "B.Voc.",
  "B.Pharm.",
  "MBBS",
  "BDS",
  "BAMS",
  "BHMS",
  "BUMS",
  "BPT",
  "B.Sc. Nursing",
  "B.V.Sc. & AH",
  "B.Optom.",
  "GNM",
  "ANM",
  "B.Ed.",
  "BSW",
  "B.P.Ed.",
  "B.Sc. Agriculture",
  "BHMCT (Hotel Management & Catering Technology)",
  "B.F.Sc. (Fisheries Science)",
  "LLB",
  "CA (Chartered Accountant)",
  "CS (Company Secretary)",
  "CMA",
  "CFA (Chartered Financial Analyst)",
  "M.A.",
  "M.Sc.",
  "M.Com.",
  "MBA",
  "Executive MBA",
  "PGDM",
  "PGDCA",
  "MCA",
  "M.Tech.",
  "M.E.",
  "M.Arch.",
  "M.Des.",
  "MFA",
  "M.Pharm.",
  "Pharm.D",
  "MD",
  "MS",
  "MDS",
  "M.V.Sc. (Veterinary)",
  "M.Sc. Nursing",
  "Post Basic B.Sc. Nursing",
  "MSW",
  "M.P.Ed.",
  "M.Lib.Sc.",
  "M.Sc. Agriculture",
  "LLM",
  "MPhil",
  "PhD / Doctorate",
  "D.Sc. / D.Litt. (Post-Doctoral)",
  "Hifz-ul-Quran (Hafiz)",
  "Alima Course",
  "Aalim Course",
  "Fazil",
  "Kamil",
  "Dars-e-Nizami",
  "Shahadatul Aalamiyyah (Alimiyyah)",
  "Mufti / Ifta Course",
  "Qari Course (Tajweed & Recitation)",
  "Diploma in Islamic Studies",
  "Diploma in Arabic Language",
  "Certificate Course",
  "Other",
];

export async function ensureDegreeDefaults() {
  const count = await Degree.count();
  if (count > 0) return;
  await Promise.all(DEFAULTS.map((name, i) => Degree.create({ name, sortOrder: i })));
}
