import EmailTemplate from "../models/EmailTemplate.js";
import EmailSettings from "../models/EmailSettings.js";

const DEFAULT_TEMPLATES = [
  {
    key: "otp_verification",
    name: "OTP Verification",
    purpose: "Sent when a user registers with an email address, to verify ownership before activating the account.",
    subject: "Your Masjid My Community verification code",
    heading: "Verify Your Account",
    message:
      "Welcome to {{platform_name}}.\n\nTo complete your registration and verify your account, please use the verification code below. This code is valid for 5 minutes — please do not share it with anyone. If you did not request this, you can safely ignore this email.",
    ctaText: null,
    ctaLink: null,
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Fa inna ma'al-'usri yusra",
    quoteTranslation: "Indeed, with hardship comes ease.",
    quoteSource: "Qur'an 94:5 (Surah Ash-Sharh)",
    status: "active",
    availableVariables: ["user_name", "otp_code", "platform_name", "current_year"],
  },
  {
    key: "welcome_registration",
    name: "Registration Successful / Welcome Email",
    purpose: "Sent automatically once a user's account is verified and successfully activated.",
    subject: "Welcome to Masjid My Community!",
    heading: "Welcome to Masjid My Community!",
    message:
      "Your account has been successfully verified and registered.\n\nYou are now part of a growing community working towards a shared vision: Empowering Masjids. Strengthening Communities.\n\n{{platform_name}} connects communities, supporters and masjids to create meaningful, transparent impact — from registering a masjid, to launching a campaign, to tracking real progress.",
    ctaText: "Start Your Journey",
    ctaLink: "http://localhost:5173/account",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Man banaa masjidan lillah, banallahu lahu baytan fil-jannah",
    quoteTranslation: "Whoever builds a masjid for the sake of Allah, Allah will build for him a house in Paradise.",
    quoteSource: "Sahih Muslim 533; also narrated in Sahih al-Bukhari 450",
    status: "active",
    availableVariables: ["user_name", "platform_name", "current_year"],
  },
  {
    key: "account_status_changed",
    name: "Account Status Changed",
    purpose: "Sent whenever an admin changes a user account's status — activated, deactivated, or suspended.",
    subject: "Your {{platform_name}} account status has been updated",
    heading: "Account Status Updated",
    message: "Your account status has been changed to: {{account_status}}.\n\n{{status_detail}}",
    ctaText: "Go to My Account",
    ctaLink: "http://localhost:5173/account",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "account_status", "status_detail", "platform_name", "current_year"],
  },
  {
    key: "masjid_submitted_admin",
    name: "New Masjid Submitted – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever a user submits a masjid for review.",
    subject: "New masjid submitted for review: {{masjid_name}}",
    heading: "New Masjid Submitted for Review",
    message:
      "A new masjid has been submitted and is awaiting your review.\n\nMasjid Name: {{masjid_name}}\nMasjid ID: {{masjid_id}}\nCategory: {{category}}\nSubmitted By: {{submitted_by}}\nSubmitted On: {{submission_date}}",
    ctaText: "Review This Masjid",
    ctaLink: "http://localhost:5173/admin/masjids/{{masjid_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["masjid_name", "masjid_id", "category", "submitted_by", "submission_date", "platform_name", "current_year"],
  },
  {
    key: "masjid_submitted_user",
    name: "Masjid Submission Acknowledgement – User",
    purpose: "Sent automatically to the user right after they submit a masjid for review.",
    subject: "We've received your masjid submission: {{masjid_name}}",
    heading: "Your Masjid Has Been Submitted",
    message:
      "Your Masjid has been successfully submitted. Our admin team will review your submission and get back to you within 48 hours.\n\nMasjid Name: {{masjid_name}}\nMasjid ID: {{masjid_id}}\nSubmitted On: {{submission_date}}\nCurrent Status: {{status}}",
    ctaText: "View My Masjid",
    ctaLink: "http://localhost:5173/account/my-masjids/{{masjid_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Wa man banaa lillahi masjidan",
    quoteTranslation: "Whoever builds a masjid seeking the pleasure of Allah, Allah builds for him a house in Paradise.",
    quoteSource: "Sahih al-Bukhari 450; Sahih Muslim 533",
    status: "active",
    availableVariables: ["user_name", "masjid_name", "masjid_id", "submission_date", "status", "platform_name", "current_year"],
  },
  {
    key: "masjid_changes_requested_user",
    name: "Masjid Changes Requested – User",
    purpose: "Sent automatically to the user whenever an admin requests changes to one of their masjid submissions.",
    subject: "Action needed: changes requested for {{masjid_name}}",
    heading: "Changes Requested for Your Masjid",
    message:
      "An admin has reviewed your masjid submission and requested some changes before it can be approved.\n\nMasjid Name: {{masjid_name}}\nMasjid ID: {{masjid_id}}\nRequested On: {{request_date}}\n\nChanges Requested:\n{{changes_requested}}",
    ctaText: "View Change Request",
    ctaLink: "http://localhost:5173/account/my-masjids/{{masjid_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "masjid_name", "masjid_id", "changes_requested", "request_date", "platform_name", "current_year"],
  },
  {
    key: "campaign_submitted_admin",
    name: "New Campaign Submitted – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever a user submits a fundraising campaign for review.",
    subject: "New Campaign Submitted – Action Required: {{campaign_title}}",
    heading: "New Campaign Submitted for Review",
    message:
      "A new fundraising campaign has been submitted and is awaiting your review.\n\nCampaign Title: {{campaign_title}}\nCampaign ID: {{campaign_id}}\nMasjid: {{masjid_name}}\nSubmitted By: {{submitted_by}}\nCategory: {{category}}\nFundraising Classification: {{donation_type}}\nFunding Goal: {{goal_amount}}\nSubmitted On: {{submission_date}}\nCurrent Status: {{status}}\n\nDescription:\n{{description}}",
    ctaText: "Review This Campaign",
    ctaLink: "http://localhost:5173/admin/campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["campaign_title", "campaign_id", "masjid_name", "submitted_by", "category", "donation_type", "goal_amount", "submission_date", "status", "description", "platform_name", "current_year"],
  },
  {
    key: "campaign_submitted_user",
    name: "Campaign Submission Received – User",
    purpose: "Sent automatically to the user right after they submit a fundraising campaign for review.",
    subject: "Campaign Submission Received – Under Review",
    heading: "Your Campaign Has Been Submitted",
    message:
      "Thank you for submitting your campaign. Your campaign has been successfully received and is currently under review. Our team will review the submitted information — including the Islamic and legal guidelines — and get back to you regarding the next steps.\n\nCampaign Name: {{campaign_title}}\nSubmission Reference: #{{campaign_id}}\nMasjid: {{masjid_name}}\nSubmitted On: {{submission_date}}\nCurrent Status: {{status}}\n\nWhat happens next: our review team checks the campaign against our Islamic, legal, and content guidelines, typically within 48 hours. You'll receive an email as soon as a decision is made, and you can track the status any time from My Campaigns.",
    ctaText: "View My Campaign",
    ctaLink: "http://localhost:5173/account/my-campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Man dalla ala khayrin fa lahu mithlu ajri faa'ilihi",
    quoteTranslation: "Whoever guides someone to goodness will have a reward like the one who did it.",
    quoteSource: "Sahih Muslim 1893",
    status: "active",
    availableVariables: ["user_name", "campaign_title", "campaign_id", "masjid_name", "submission_date", "status", "platform_name", "current_year"],
  },
  {
    key: "campaign_changes_requested_user",
    name: "Campaign Changes Requested – User",
    purpose: "Sent automatically to the user whenever an admin requests changes to one of their fundraising campaigns.",
    subject: "Action needed: changes requested for {{campaign_title}}",
    heading: "Changes Requested for Your Campaign",
    message:
      "An admin has reviewed your campaign submission and requested some changes before it can be approved.\n\nCampaign Name: {{campaign_title}}\nCampaign ID: {{campaign_id}}\nMasjid: {{masjid_name}}\nRequested On: {{request_date}}\n\nChanges Requested:\n{{changes_requested}}\n\nPlease review and update your campaign, then resubmit it for review.",
    ctaText: "View Change Request",
    ctaLink: "http://localhost:5173/account/my-campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "campaign_title", "campaign_id", "masjid_name", "changes_requested", "request_date", "platform_name", "current_year"],
  },
  {
    key: "campaign_change_response_admin",
    name: "User Responded to Change Request – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever a user resubmits a campaign after changes were requested.",
    subject: "Campaign resubmitted after requested changes: {{campaign_title}}",
    heading: "User Responded to a Change Request",
    message:
      "A user has updated and resubmitted a campaign that previously had changes requested.\n\nCampaign Title: {{campaign_title}}\nCampaign ID: {{campaign_id}}\nMasjid: {{masjid_name}}\nSubmitted By: {{submitted_by}}\nResponded On: {{response_date}}\nCurrent Status: {{status}}\n\nOriginal Changes Requested:\n{{original_request}}\n\nThe campaign has been updated accordingly and is awaiting your re-review.",
    ctaText: "Review Response",
    ctaLink: "http://localhost:5173/admin/campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["campaign_title", "campaign_id", "masjid_name", "submitted_by", "response_date", "status", "original_request", "platform_name", "current_year"],
  },
  {
    key: "campaign_approved_user",
    name: "Campaign Approved – User",
    purpose: "Sent automatically to the user when their fundraising campaign is approved and goes live.",
    subject: "Alhamdulillah! Your campaign is now live: {{campaign_title}}",
    heading: "Your Campaign Is Now Live",
    message:
      "Alhamdulillah — your campaign has been reviewed and approved. It is now live on {{platform_name}} and ready to receive support from the community.\n\nCampaign Name: {{campaign_title}}\nMasjid: {{masjid_name}}\nApproved On: {{approval_date}}\n\nShare your campaign with your community to help it reach its goal, insha'Allah.",
    ctaText: "View My Campaign",
    ctaLink: "http://localhost:5173/account/my-campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Alladhina yunfiquna amwalahum fi sabilillah",
    quoteTranslation: "Those who spend their wealth in the way of Allah — their reward is with their Lord.",
    quoteSource: "Qur'an 2:262",
    status: "active",
    availableVariables: ["user_name", "campaign_title", "campaign_id", "masjid_name", "approval_date", "platform_name", "current_year"],
  },
  {
    key: "campaign_rejected_user",
    name: "Campaign Rejected – User",
    purpose: "Sent automatically to the user when their fundraising campaign is rejected.",
    subject: "Update on your campaign: {{campaign_title}}",
    heading: "Your Campaign Was Not Approved",
    message:
      "After careful review, we're unable to approve your campaign at this time.\n\nCampaign Name: {{campaign_title}}\nMasjid: {{masjid_name}}\nReviewed On: {{rejection_date}}\n\nReason:\n{{rejection_reason}}\n\nIf you believe this was a mistake or would like guidance on resubmitting a compliant campaign, please contact our support team.",
    ctaText: "View My Campaigns",
    ctaLink: "http://localhost:5173/account/my-campaigns",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "campaign_title", "campaign_id", "masjid_name", "rejection_reason", "rejection_date", "platform_name", "current_year"],
  },
  {
    key: "campaign_status_updated_user",
    name: "Campaign Status Updated – User",
    purpose: "Sent automatically to the user whenever an admin changes a live campaign's status (paused, resumed, completed, or cancelled).",
    subject: "Your campaign status has changed: {{campaign_title}}",
    heading: "Campaign Status Updated",
    message:
      "The status of your campaign has been updated by an admin.\n\nCampaign Name: {{campaign_title}}\nMasjid: {{masjid_name}}\nNew Status: {{new_status}}\nUpdated On: {{status_date}}\n\nYou can view full details and progress any time from My Campaigns.",
    ctaText: "View My Campaign",
    ctaLink: "http://localhost:5173/account/my-campaigns/{{campaign_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "campaign_title", "campaign_id", "masjid_name", "new_status", "status_date", "platform_name", "current_year"],
  },
  {
    key: "concern_submitted_admin",
    name: "New Concern Submitted – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever someone submits a concern through Raise a Concern.",
    subject: "New Concern Submitted – Action Required: {{subject}}",
    heading: "New Concern Submitted",
    message:
      "A new concern has been submitted and is awaiting your review.\n\nConcern ID: {{concern_id}}\nSubmitted By: {{user_name}}\nContact: {{user_contact}}\nConcern Type: {{concern_type}}\nSubject: {{subject}}\nRelated To: {{related_reference}}\nSubmitted On: {{submission_date}}\nCurrent Status: {{status}}\n\nDescription:\n{{description}}",
    ctaText: "View Concern",
    ctaLink: "http://localhost:5173/admin/concerns/{{concern_id}}",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["concern_id", "user_name", "user_contact", "concern_type", "subject", "related_reference", "submission_date", "status", "description", "platform_name", "current_year"],
  },
  {
    key: "concern_submitted_user",
    name: "Concern Submission Acknowledgement – User",
    purpose: "Sent automatically to the submitter right after they raise a concern.",
    subject: "We have received your concern — {{concern_id}}",
    heading: "We Have Received Your Concern",
    message:
      "Thank you for bringing this to our attention. Your concern has been received and is currently being reviewed by our team — every report is looked at by a person, not just logged.\n\nConcern ID: {{concern_id}}\nConcern Type: {{concern_type}}\nSubject: {{subject}}\nSubmitted On: {{submission_date}}\nCurrent Status: {{status}}\n\nWhat happens next: our team will review the details you've shared and, if needed, reach out to you or the masjid committee for more information. You'll hear back at this email address, typically within 48 hours.",
    ctaText: "Contact Support",
    ctaLink: "mailto:hello@masjidmycommunity.org",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: true,
    quoteTransliteration: "Ad-deenu an-naseehah",
    quoteTranslation: "Religion is sincerity and sincere counsel.",
    quoteSource: "Sahih Muslim 55",
    status: "active",
    availableVariables: ["user_name", "concern_id", "concern_type", "subject", "submission_date", "status", "platform_name", "current_year"],
  },
  {
    key: "concern_resolved_user",
    name: "Concern Resolved – User",
    purpose: "Sent automatically to the submitter when an admin marks their concern as resolved.",
    subject: "Your concern has been resolved — {{concern_id}}",
    heading: "Your Concern Has Been Reviewed and Resolved",
    message:
      "Your concern has been reviewed and resolved. This email serves as official confirmation of that outcome.\n\nConcern ID: {{concern_id}}\nConcern Type: {{concern_type}}\nOriginal Subject: {{subject}}\nSubmitted On: {{submission_date}}\nResolution Status: Resolved\nResolved On: {{resolution_date}}\n\nResolution Notes:\n{{admin_remarks}}\n\nIf you have any further questions about this outcome, please don't hesitate to reach out to our support team.",
    ctaText: "Contact Support",
    ctaLink: "mailto:hello@masjidmycommunity.org",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nNeed help? Contact us at hello@masjidmycommunity.org\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "concern_id", "concern_type", "subject", "submission_date", "resolution_date", "admin_remarks", "platform_name", "current_year"],
  },
  {
    key: "contact_message_admin",
    name: "New Contact Message – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever someone submits the Contact page form.",
    subject: "New contact message: {{topic}} — {{user_name}}",
    heading: "New Message from the Contact Page",
    message:
      "Someone has sent a message through the Contact page.\n\nName: {{user_name}}\nEmail: {{user_contact}}\nTopic: {{topic}}\nSent On: {{submission_date}}\n\nMessage:\n{{message_body}}",
    ctaText: null,
    ctaLink: null,
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["user_name", "user_contact", "topic", "submission_date", "message_body", "platform_name", "current_year"],
  },
  {
    key: "moderation_threshold_reached_admin",
    name: "Content Auto-Hidden – Admin Notification",
    purpose: "Sent to the configured admin notification email whenever a masjid, campaign, or Wall post reaches the configured report threshold and is automatically hidden pending review.",
    subject: "Action Required: {{content_type}} \"{{content_name}}\" auto-hidden after {{report_count}} reports",
    heading: "Content Automatically Hidden — Review Needed",
    message:
      "The following content has reached the configured community-report threshold and has been automatically hidden from public view pending your review. The underlying record has not been deleted.\n\nContent Type: {{content_type}}\nContent: {{content_name}}\nReport Count: {{report_count}}\nConfigured Threshold: {{threshold}}\nHidden On: {{hidden_date}}\n\nPlease review the reported content and take an appropriate moderation action.",
    ctaText: "Review Reported Content",
    ctaLink: "http://localhost:5173/admin/moderation",
    footerText:
      "{{platform_name}} — Empowering Masjids. Strengthening Communities.\nThis is an automated admin notification from {{platform_name}}.\n© {{current_year}} {{platform_name}}. All rights reserved.",
    quoteEnabled: false,
    quoteTransliteration: null,
    quoteTranslation: null,
    quoteSource: null,
    status: "active",
    availableVariables: ["content_type", "content_name", "report_count", "threshold", "hidden_date", "platform_name", "current_year"],
  },
];

export async function ensureEmailDefaults() {
  for (const tpl of DEFAULT_TEMPLATES) {
    await EmailTemplate.findOrCreate({ where: { key: tpl.key }, defaults: tpl });
  }
  await EmailSettings.findOrCreate({ where: { id: 1 }, defaults: { id: 1 } });
}
