import Faq from "../models/Faq.js";

// Starter content so the FAQ page and knowledge base aren't empty on a
// fresh install — admins can edit/add/remove freely afterward. isFeatured
// picks the 4 that show as "Popular Questions" on Home.jsx's teaser.
// Answers are written as short paragraphs (not one-liners) since they also
// feed the "Ask AI" retrieval corpus — more context per FAQ means better
// grounded answers, not just a friendlier public FAQ page.
export const FAQ_DEFAULTS = [
  ["About Masjid My Community", "What is Masjid My Community?", "Masjid My Community is an online platform that connects masjids with the people who support them. Masjids can register, verify their identity, share what they currently need — whether that's construction, repairs, educational programs, or community welfare — and raise funds directly from supporters around the world. Donors, in turn, can discover masjids they trust, follow specific campaigns, and see exactly how their contributions are being used through progress updates, photos, and itemized expense reports. Beyond fundraising, the platform also gives masjids simple tools for day-to-day management — tracking donations, communicating with their community, and building the kind of transparency that helps supporters give with confidence.", "compass", true],
  ["About Masjid My Community", "Who runs Masjid My Community?", "Masjid My Community is built and maintained by a small team focused on solving a problem many masjids share: they're often run by a handful of dedicated volunteers who don't have the time, tools, or technical background to manage fundraising, communication, and reporting on their own. The platform exists to close that gap — giving every masjid, regardless of size or resources, access to the same professional-grade tools for managing funds, reaching their community, and planning for the future in one simple, trusted place. We don't run individual masjids or make decisions on their behalf; each masjid registers, manages its own campaigns, and stays fully in control of its own content and finances.", "building", false],
  ["Vision & Mission", "What is the platform's main goal?", "Our main goal is to help every masjid become stronger, better run, and financially resilient — able to generate the steady, predictable income it needs to serve its community, rather than depending only on occasional, one-time donations. Many masjids operate on tight, unpredictable budgets, which makes it hard to plan ahead for maintenance, staff, or programs. We want to change that by giving masjids modern tools for fundraising, governance, and communication, so they can build long-term relationships with supporters instead of constantly starting from zero. Ultimately, a financially stable masjid is better equipped to serve its community — through worship, education, and social support — for generations to come.", "flag", true],
  ["Vision & Mission", "What does Masjid My Community value most?", "Trust, transparency, community participation, and long-term sustainability guide everything we build. In practice, that means every feature on the platform is designed with a clear question in mind: does this help a masjid become more accountable, more connected to its community, and more capable of sustaining itself over time — rather than dependent on any single source of support? We believe that when donors can clearly see how funds are used, and when communities feel genuinely involved rather than just asked for money, masjids become stronger and more resilient institutions in the long run.", "shieldCheck", false],
  ["Masjid Empowerment", "How does the platform empower masjids?", "The platform empowers masjids by giving them the same kind of professional tools that larger, well-resourced organizations already use — without requiring technical expertise or a large budget. This includes clear governance and financial reporting so donors can see exactly how funds are used, simple campaign management for raising money toward specific needs, resource and expense tracking to keep everything accountable, and easy ways for community members to get involved and stay informed. Together, these tools help masjids move away from relying purely on unpredictable, one-time donations and instead build steady, long-term income and a stronger, more engaged community around them.", "chartUp", true],
  ["Masjid Empowerment", "Can a masjid run more than one campaign?", "Yes. Once a masjid has completed our verification process, it isn't limited to a single campaign — it can launch as many campaigns as it needs, for different purposes at the same time. For example, a masjid might run one campaign for a construction project, another for an education program, and a third for a welfare initiative, all running simultaneously. Each campaign has its own funding goal, timeline, and itemized expense reporting, so donors can clearly see which campaign their contribution supports and how that specific campaign's funds are being used.", "wallet", false],
  ["Community", "How does Masjid My Community support the wider community, not just donations?", "Beyond fundraising, the platform is designed to help masjids stay closely connected to their wider community — reflecting the masjid's traditional role as far more than just a place of worship. Historically, masjids have served as centers for learning, guidance, social support, and cooperation, and our tools are built to strengthen that role in a modern context: sharing community updates, promoting educational programs and events, and making it easier for members to get involved beyond simply donating. The goal is for a masjid on the platform to feel like an active hub for its community, not just a destination for fundraising.", "people", false],
  ["Community", "Can donors track the impact of their support?", "Yes — transparency around impact is a core part of how the platform works. Every donation is linked directly to the specific campaign it supported, and donors can return to that campaign at any time to see its progress: written updates from the masjid, photos documenting the work as it happens, and itemized expense reports that show exactly where the money went. This means a donor isn't just giving and hoping for the best — they can follow their contribution from the moment they give until the project is completed, which builds trust and encourages ongoing support.", "globe", false],
  ["Privacy & Security", "How is my personal information protected?", "Protecting your personal and financial information is a core part of how the platform is built. Payment details are handled entirely by PCI-DSS compliant payment processors — the same industry security standard used by major banks and payment providers — and Masjid My Community never stores your full card number or bank account details on our own servers. We only collect the information genuinely needed to process donations, verify masjid registrations, and keep the platform secure, and we never share your personal data for unrelated purposes. For the complete picture of what information is collected, how long it's kept, and the choices you have, please see our full Privacy Policy.", "shieldCheck", true],
  ["Privacy & Security", "Does Masjid My Community sell my data?", "No — Masjid My Community does not sell your personal information to third parties, under any circumstances. Your data is used strictly for legitimate platform purposes: processing your donations, verifying masjid registrations, communicating important updates about campaigns or your account, and keeping the platform secure from fraud and abuse. We do not share your information with advertisers or data brokers, and any third-party service we do rely on (such as a payment processor) is bound by its own strict security and privacy obligations. Full details are available in our Privacy Policy.", "shieldCheck", false],
  ["Terms & Policies", "Are my donations refundable?", "Donations made through the platform are voluntary contributions, and as a general rule, they are non-refundable once a campaign has received the funds — this protects masjids that may have already begun spending donated funds on their stated project. That said, there are limited exceptions: if a donation was made in error, such as a duplicate charge or an incorrect amount due to a processing mistake, or where a refund is required by applicable law, we will review the situation and work toward a resolution. If you believe you've made a donation in error, we encourage you to contact us as soon as possible so we can look into it. Full details are available in our Terms of Use.", "book", false],
  ["Terms & Policies", "How are cookies used on this site?", "Cookies are small pieces of data stored in your browser that help the platform work properly and improve your experience. We use them to keep you signed in between visits, remember your preferences — such as your selected language — and help us understand, in aggregate, how the platform is being used so we can improve it over time. Some cookies are essential for the site to function, while others are optional and only used with your consent. You're always in control: you can review and update your cookie preferences at any time through our cookie settings, and our full Cookie Policy explains exactly what each category of cookie does.", "monitor", false],
  ["Platform Features", "What languages does the platform support?", "Masjid My Community is available in English, Hindi, Urdu, and Arabic, with Urdu and Arabic fully supported in right-to-left (RTL) layout for a natural reading experience. This means more people — masjid administrators, donors, and community members — can browse campaigns, register a masjid, make a donation, and get support entirely in the language they're most comfortable with, rather than being limited to English. You can switch languages at any time using the language selector in the site footer, and your choice is remembered for future visits. We plan to keep expanding language support over time as the community grows.", "globe", false],
  ["Platform Features", "How do I raise a concern about a campaign or masjid?", "If you come across a campaign or masjid that seems suspicious, inaccurate, or otherwise concerning, use the \"Raise a Concern\" page to report it. Simply describe the issue and select the category that best fits your concern — such as a payment problem, incorrect information, or a technical issue — and our team will review it directly. Every concern is looked into individually and resolved as quickly as possible, and where appropriate, we take corrective action to protect the integrity of the platform. This reporting system exists precisely because trust is central to how Masjid My Community works — it gives every user a direct way to help keep the platform accountable and trustworthy for everyone.", "shieldCheck", false],
  ["Getting Started", "How do I register my masjid?", "Registering your masjid starts with creating a free account on the platform. From there, you'll complete our masjid registration form, which includes basic information about the masjid, details about its managing committee, and supporting documentation that helps us verify the masjid is legitimate — this verification step exists to protect donors and maintain trust across the platform. Once your masjid has been reviewed and verified by our team, you'll gain full access to launch fundraising campaigns, manage your masjid's public profile, and start reaching supporters both locally and internationally.", "building", true],
  ["Getting Started", "How do I make a donation?", "Making a donation is simple. Start by browsing active campaigns — you can search by masjid, category, or location — and choose one that matters to you. Once you've selected a campaign, choose the amount you'd like to give, and if it's relevant to your own giving, you can optionally tag your donation as Zakat or Sadaqah for your personal records. Finally, complete your payment securely through our PCI-DSS compliant payment processor; you'll receive a confirmation, and you can return anytime to see how your donation is being used as the campaign progresses.", "wallet", false],
];

export async function ensureFaqDefaults() {
  const count = await Faq.count();
  if (count === 0) {
    await Promise.all(
      FAQ_DEFAULTS.map(([category, question, answer, icon, isFeatured], i) =>
        Faq.create({ category, question, answer, icon, isFeatured, sortOrder: i })
      )
    );
  }
}
