import FieldOfStudy from "../models/FieldOfStudy.js";

const DEFAULTS = [
  "Computer Science",
  "Information Technology",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Electronics & Communication",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Automobile Engineering",
  "Biomedical Engineering",
  "Biotechnology Engineering",
  "Industrial Engineering",
  "Instrumentation Engineering",
  "Metallurgical Engineering",
  "Mining Engineering",
  "Petroleum Engineering",
  "Textile Engineering",
  "Environmental Engineering",
  "Data Science",
  "Artificial Intelligence & Machine Learning",
  "Robotics",
  "Cybersecurity",
  "Cloud Computing",
  "Physics",
  "Chemistry",
  "Biology",
  "Mathematics",
  "Statistics",
  "Zoology",
  "Botany",
  "Microbiology",
  "Biotechnology",
  "Biochemistry",
  "Genetics",
  "Environmental Science",
  "Geology",
  "Geography",
  "Astronomy",
  "Forensic Science",
  "Food Science & Technology",
  "Nutrition & Dietetics",
  "Commerce",
  "Business Administration",
  "Economics",
  "Finance",
  "Accounting",
  "Marketing",
  "Human Resource Management",
  "International Business",
  "Banking & Insurance",
  "Supply Chain Management",
  "Entrepreneurship",
  "Actuarial Science",
  "Arts / Humanities",
  "English Literature",
  "Hindi Literature",
  "Urdu Literature",
  "Arabic Literature",
  "Persian Literature",
  "Sanskrit",
  "History",
  "Political Science",
  "Sociology",
  "Philosophy",
  "Psychology",
  "Anthropology",
  "Public Administration",
  "Linguistics",
  "Journalism & Mass Communication",
  "Social Work",
  "Law",
  "Criminology",
  "Medicine",
  "Dentistry",
  "Ayurveda",
  "Homeopathy",
  "Unani Medicine",
  "Nursing",
  "Pharmacy",
  "Physiotherapy",
  "Veterinary Science",
  "Public Health",
  "Medical Lab Technology",
  "Radiology & Imaging Technology",
  "Optometry",
  "Education",
  "Physical Education",
  "Special Education",
  "Early Childhood Education",
  "Islamic Studies",
  "Arabic & Islamic Theology",
  "Quranic Studies",
  "Hadith Studies",
  "Islamic Jurisprudence (Fiqh)",
  "Comparative Religion",
  "Fine Arts",
  "Fashion Design",
  "Interior Design",
  "Graphic Design",
  "Animation & Multimedia",
  "Performing Arts (Music & Dance)",
  "Agriculture",
  "Horticulture",
  "Forestry",
  "Fisheries Science",
  "Dairy Technology",
  "Agricultural Engineering",
  "Hotel Management",
  "Tourism & Travel Management",
  "Culinary Arts",
  "Architecture",
  "Urban & Regional Planning",
  "Library Science",
  "Sports Science",
  "Aviation / Aeronautics",
  "Other",
];

export async function ensureFieldOfStudyDefaults() {
  const count = await FieldOfStudy.count();
  if (count > 0) return;
  await Promise.all(DEFAULTS.map((name, i) => FieldOfStudy.create({ name, sortOrder: i })));
}
