import Institution from "../models/Institution.js";

const DEFAULTS = [
  "Indian Institute of Technology (IIT) Bombay",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Kanpur",
  "Indian Institute of Technology (IIT) Kharagpur",
  "Indian Institute of Technology (IIT) Madras",
  "Indian Institute of Technology (IIT) Roorkee",
  "Indian Institute of Technology (IIT) Guwahati",
  "Indian Institute of Technology (IIT) Hyderabad",
  "Indian Institute of Technology (IIT) Indore",
  "Indian Institute of Technology (IIT-BHU) Varanasi",
  "Indian Institute of Technology (IIT) Gandhinagar",
  "Indian Institute of Technology (IIT) Ropar",
  "Indian Institute of Technology (IIT) Bhubaneswar",
  "Indian Institute of Technology (IIT) Patna",
  "Indian Institute of Technology (IIT) Jodhpur",
  "Indian Institute of Technology (IIT) Mandi",
  "Indian Institute of Technology (IIT-ISM) Dhanbad",
  "Indian Institute of Technology (IIT) Bhilai",
  "Indian Institute of Technology (IIT) Goa",
  "Indian Institute of Technology (IIT) Jammu",
  "Indian Institute of Technology (IIT) Palakkad",
  "Indian Institute of Technology (IIT) Tirupati",
  "Indian Institute of Technology (IIT) Dharwad",
  "Indian Institute of Management (IIM) Ahmedabad",
  "Indian Institute of Management (IIM) Bangalore",
  "Indian Institute of Management (IIM) Calcutta",
  "Indian Institute of Management (IIM) Lucknow",
  "Indian Institute of Management (IIM) Kozhikode",
  "Indian Institute of Management (IIM) Indore",
  "Indian Institute of Management (IIM) Shillong",
  "Indian Institute of Management (IIM) Rohtak",
  "Indian Institute of Management (IIM) Ranchi",
  "Indian Institute of Management (IIM) Raipur",
  "Indian Institute of Management (IIM) Tiruchirappalli",
  "Indian Institute of Management (IIM) Udaipur",
  "Indian Institute of Management (IIM) Kashipur",
  "Indian Institute of Management (IIM) Nagpur",
  "Indian Institute of Management (IIM) Bodh Gaya",
  "Indian Institute of Management (IIM) Sambalpur",
  "Indian Institute of Management (IIM) Sirmaur",
  "Indian Institute of Management (IIM) Amritsar",
  "Indian Institute of Management (IIM) Jammu",
  "Indian Institute of Management (IIM) Visakhapatnam",
  "Indian Institute of Science (IISc) Bangalore",
  "National Institute of Technology (NIT) Tiruchirappalli",
  "National Institute of Technology (NIT) Warangal",
  "National Institute of Technology Karnataka (NITK) Surathkal",
  "National Institute of Technology (NIT) Rourkela",
  "National Institute of Technology (NIT) Calicut",
  "National Institute of Technology (NIT) Durgapur",
  "National Institute of Technology (NIT) Kurukshetra",
  "Malaviya National Institute of Technology (MNIT) Jaipur",
  "Motilal Nehru National Institute of Technology (MNNIT) Allahabad",
  "Maulana Azad National Institute of Technology (MANIT) Bhopal",
  "Visvesvaraya National Institute of Technology (VNIT) Nagpur",
  "National Institute of Technology (NIT) Silchar",
  "National Institute of Technology (NIT) Agartala",
  "National Institute of Technology (NIT) Hamirpur",
  "Dr. B. R. Ambedkar National Institute of Technology (NIT) Jalandhar",
  "National Institute of Technology (NIT) Patna",
  "National Institute of Technology (NIT) Raipur",
  "National Institute of Technology (NIT) Srinagar",
  "National Institute of Technology Delhi (NIT Delhi)",
  "National Institute of Technology Goa (NIT Goa)",
  "International Institute of Information Technology (IIIT) Hyderabad",
  "International Institute of Information Technology Bangalore (IIIT-B)",
  "Indraprastha Institute of Information Technology (IIIT) Delhi",
  "Indian Institute of Information Technology (IIIT) Allahabad",
  "Atal Bihari Vajpayee Indian Institute of Information Technology and Management (IIITM) Gwalior",
  "Indian Institute of Information Technology (IIIT) Kota",
  "Indian Institute of Information Technology Vadodara (IIITV)",
  "Delhi University",
  "Jawaharlal Nehru University",
  "Jamia Millia Islamia",
  "Aligarh Muslim University",
  "Banaras Hindu University",
  "University of Hyderabad",
  "Pondicherry University",
  "Visva-Bharati University",
  "Central University of Kashmir",
  "Central University of Kerala",
  "Central University of Punjab",
  "Central University of Rajasthan",
  "Central University of Gujarat",
  "Central University of Haryana",
  "Central University of Himachal Pradesh",
  "Central University of Jammu",
  "Central University of Jharkhand",
  "Central University of Karnataka",
  "Central University of Odisha",
  "Central University of South Bihar",
  "Central University of Tamil Nadu",
  "Assam University",
  "Manipur University",
  "Mizoram University",
  "Nagaland University",
  "North Eastern Hill University",
  "Rajiv Gandhi University",
  "Sikkim University",
  "Tripura University",
  "Babasaheb Bhimrao Ambedkar University",
  "Maulana Azad National Urdu University",
  "National Sanskrit University",
  "University of Mumbai",
  "University of Calcutta",
  "University of Madras",
  "Anna University",
  "Osmania University",
  "Jadavpur University",
  "Panjab University",
  "Lucknow University",
  "Allahabad University",
  "Gujarat University",
  "University of Rajasthan",
  "Savitribai Phule Pune University",
  "University of Kerala",
  "Bangalore University",
  "Andhra University",
  "Utkal University",
  "Gauhati University",
  "Patna University",
  "Ranchi University",
  "Barkatullah University",
  "Devi Ahilya Vishwavidyalaya",
  "Guru Nanak Dev University",
  "Punjabi University Patiala",
  "Tezpur University",
  "Dibrugarh University",
  "SNDT Women's University",
  "Karnatak University",
  "Mangalore University",
  "University of Mysore",
  "Kuvempu University",
  "Sri Venkateswara University",
  "Kakatiya University",
  "Rashtrasant Tukadoji Maharaj Nagpur University",
  "Shivaji University",
  "North Maharashtra University",
  "Dr. Babasaheb Ambedkar Marathwada University",
  "Sardar Patel University",
  "Maharaja Sayajirao University of Baroda",
  "Veer Narmad South Gujarat University",
  "Jai Narain Vyas University",
  "Mohanlal Sukhadia University",
  "Chaudhary Charan Singh University",
  "Dr. Bhimrao Ambedkar University, Agra",
  "Mahatma Jyotiba Phule Rohilkhand University",
  "Veer Bahadur Singh Purvanchal University",
  "Rani Durgavati Vishwavidyalaya",
  "Vikram University",
  "Berhampur University",
  "Sambalpur University",
  "Fakir Mohan University",
  "University of North Bengal",
  "University of Burdwan",
  "University of Kalyani",
  "Vidyasagar University",
  "Magadh University",
  "Veer Kunwar Singh University",
  "Chhatrapati Shahu Ji Maharaj University",
  "Dr. Ram Manohar Lohia Avadh University",
  "Mahatma Gandhi Kashi Vidyapith",
  "Bundelkhand University",
  "Kumaun University",
  "HNB Garhwal University",
  "Himachal Pradesh University",
  "University of Jammu",
  "University of Kashmir",
  "Bharathiar University",
  "Bharathidasan University",
  "Madurai Kamaraj University",
  "Manonmaniam Sundaranar University",
  "Alagappa University",
  "Periyar University",
  "Annamalai University",
  "Mahatma Gandhi University, Kerala",
  "University of Calicut",
  "Kannur University",
  "Amity University",
  "Manipal Academy of Higher Education",
  "Vellore Institute of Technology (VIT)",
  "Birla Institute of Technology and Science (BITS) Pilani",
  "Symbiosis International University",
  "SRM Institute of Science and Technology",
  "Thapar Institute of Engineering and Technology",
  "Shiv Nadar University",
  "Ashoka University",
  "O.P. Jindal Global University",
  "Lovely Professional University (LPU)",
  "Chandigarh University",
  "Sharda University",
  "Galgotias University",
  "GLA University",
  "Bennett University",
  "Sathyabama Institute of Science and Technology",
  "KIIT University",
  "SASTRA Deemed University",
  "Kalinga Institute of Industrial Technology",
  "Christ University",
  "Loyola College",
  "St. Xavier's College",
  "Presidency University",
  "Fergusson College",
  "Miranda House",
  "Hindu College, Delhi",
  "St. Stephen's College, Delhi",
  "Lady Shri Ram College for Women",
  "Hansraj College",
  "Sri Venkateswara College",
  "Ramjas College",
  "Loyola College of Social Sciences",
  "All India Institute of Medical Sciences (AIIMS) Delhi",
  "All India Institute of Medical Sciences (AIIMS) Bhopal",
  "All India Institute of Medical Sciences (AIIMS) Bhubaneswar",
  "All India Institute of Medical Sciences (AIIMS) Jodhpur",
  "All India Institute of Medical Sciences (AIIMS) Patna",
  "All India Institute of Medical Sciences (AIIMS) Raipur",
  "All India Institute of Medical Sciences (AIIMS) Rishikesh",
  "All India Institute of Medical Sciences (AIIMS) Nagpur",
  "All India Institute of Medical Sciences (AIIMS) Rajkot",
  "All India Institute of Medical Sciences (AIIMS) Guwahati",
  "Christian Medical College (CMC) Vellore",
  "Kasturba Medical College (KMC) Manipal",
  "Maulana Azad Medical College",
  "Grant Medical College, Mumbai",
  "King George's Medical University, Lucknow",
  "National Law School of India University, Bangalore",
  "NALSAR University of Law, Hyderabad",
  "National Law University, Delhi",
  "National Law University, Jodhpur",
  "West Bengal National University of Juridical Sciences (WBNUJS), Kolkata",
  "Gujarat National Law University (GNLU), Gandhinagar",
  "Hidayatullah National Law University (HNLU), Raipur",
  "Dr. Ram Manohar Lohiya National Law University, Lucknow",
  "Indian Statistical Institute (ISI) Kolkata",
  "Tata Institute of Social Sciences (TISS)",
  "Indian Institute of Science Education and Research (IISER) Pune",
  "Indian Institute of Science Education and Research (IISER) Kolkata",
  "Indian Institute of Science Education and Research (IISER) Bhopal",
  "Indian Institute of Science Education and Research (IISER) Mohali",
  "Tata Institute of Fundamental Research (TIFR)",
  "Physical Research Laboratory (PRL) Ahmedabad",
  "Jamia Hamdard",
  "Integral University",
  "Darul Uloom Deoband",
  "Darul Uloom Nadwatul Ulama, Lucknow",
  "Jamia Nizamia, Hyderabad",
  "Al-Jamia Al-Islamia, Shanthapuram",
  "Jamia Salafia, Varanasi",
  "Mazahir Uloom, Saharanpur",
  "Markazul Ma'arif, Mumbai",
  "Jamia Ashrafia, Mubarakpur",
  "Al Jamiatul Ashrafia, Mubarakpur",
  "Darul Uloom Waqf, Deoband",
  "Jamiah Islamiah Ishaatul Uloom, Akkalkuwa",
  "Dar-ul-Uloom Amjadia, Fatehpur",
  "Madrasa Aliya, Rampur",
  "Jamia Arabia Islamia, Vellore",
  "Al-Ameen Mission, West Bengal",
  "Other",
];

export async function ensureInstitutionDefaults() {
  const count = await Institution.count();
  if (count > 0) return;
  await Promise.all(DEFAULTS.map((name, i) => Institution.create({ name, sortOrder: i })));
}
